version: '3.4'
services:
  eureka-server:
    image: jjrmedeiros/eureka-server:1.0.0
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - hr-system

  api-gateway:
    image: jjrmedeiros/api-gateway:1.0.0
    ports:
      - "8765:8765"
    expose:
      - "8765"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka

  user-api:
    image: jjrmedeiros/user-api:1.0.0
    ports:
      - "8000:8000"
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - PORT=8001
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - hr-system

  payroll-api:
    image: jjrmedeiros/payroll-api:1.0.0
    ports:
      - "8100:8100"
    depends_on:
      - eureka-server
      - api-gateway
      - user-api  
    environment:
      - PORT=8100
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - hr-system

networks:
  hr-system:
    driver: bridge